"""End-to-end dataset preparation for the basketball-court CNN.

Combines three potential sources into the standard layout
``data/{train,val,test}/stage_{1..7}/*.{png,jpg}``:

  1. Synthetic — generated by the upgraded ``synthesize`` module. Always run.
  2. Kaggle — pulled with the kaggle CLI (requires ~/.kaggle/kaggle.json).
     The Kaggle source's labels are remapped to your 7 stages via a config dict.
  3. Manual — a folder of real photos you've labelled yourself, structured as
     ``manual_root/stage_{1..7}/*.{png,jpg}``. Always merged when --manual-root
     is supplied.

Usage:
  python -m app.training.prepare_data --out /app/data \
      --synthetic-train 400 --synthetic-val 80 --synthetic-test 50 \
      --kaggle-dataset rajkumarl/construction-site-images   # optional
      --manual-root /app/data/manual                        # optional

A manifest (``data/manifest.json``) is written summarising counts per stage and
per source so you can audit class balance before training.
"""
from __future__ import annotations
import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Iterable

from .synthesize import RENDERERS, generate as synth_generate
from ..stages import NUM_CLASSES, STAGES


# ---------------------------------------------------------------- remap config
# Keyword → stage-index mapping for Kaggle / Roboflow / generic construction
# datasets. Folder/file names are lowercased and matched. First match wins.
# Extend this list as you discover new datasets.
KEYWORD_TO_STAGE = {
    # stage 1 — site clearing
    "clearing": 0, "excavation": 0, "earthwork": 0, "demolition": 0, "bare": 0,
    "ground_break": 0, "groundbreaking": 0, "site_prep": 0,
    # stage 2 — sub-base
    "sub_base": 1, "subbase": 1, "gravel": 1, "compaction": 1, "leveling": 1,
    # stage 3 — slab / base layer
    "slab": 2, "concrete": 2, "rebar": 2, "formwork": 2, "foundation": 2,
    "pour": 2, "casting": 2,
    # stage 4 — surface finish
    "asphalt": 3, "paving": 3, "surface": 3, "acrylic": 3, "topcoat": 3,
    # stage 5 — line marking
    "line_marking": 4, "linemarking": 4, "painting": 4, "marking": 4,
    "court_paint": 4, "stripe": 4,
    # stage 6 — hoops
    "hoop": 5, "backboard": 5, "rim": 5, "basket": 5, "post": 5,
    # stage 7 — fencing & finals
    "fence": 6, "fencing": 6, "perimeter": 6, "lighting": 6, "complete": 6,
    "finished": 6, "final": 6,
}


def remap_label(raw_label: str) -> int | None:
    """Return the 0-indexed stage number for a raw class label, or None if no
    keyword matches (caller decides whether to drop or hand-label)."""
    norm = raw_label.lower().replace("-", "_").replace(" ", "_")
    for keyword, stage_idx in KEYWORD_TO_STAGE.items():
        if keyword in norm:
            return stage_idx
    return None


# ---------------------------------------------------------------- IO helpers
IMG_EXTS = {".jpg", ".jpeg", ".png", ".webp", ".bmp"}


def _iter_images(root: Path) -> Iterable[Path]:
    for p in root.rglob("*"):
        if p.is_file() and p.suffix.lower() in IMG_EXTS:
            yield p


def _split_indices(n: int, val_frac: float = 0.15, test_frac: float = 0.10) -> tuple[list[int], list[int], list[int]]:
    """Deterministic train/val/test split by index modulo. Avoids the cost of
    shuffling huge lists, and stays stable across runs."""
    train, val, test = [], [], []
    for i in range(n):
        # Hash-bucket: stable, ~independent of order.
        bucket = (i * 2654435761) % 1000 / 1000.0
        if bucket < test_frac:
            test.append(i)
        elif bucket < test_frac + val_frac:
            val.append(i)
        else:
            train.append(i)
    return train, val, test


def _safe_copy(src: Path, dst_dir: Path, prefix: str, idx: int) -> Path:
    dst_dir.mkdir(parents=True, exist_ok=True)
    out = dst_dir / f"{prefix}_{idx:05d}{src.suffix.lower()}"
    shutil.copy2(src, out)
    return out


# ---------------------------------------------------------------- sources
def add_synthetic(out_root: Path, train_n: int, val_n: int, test_n: int) -> dict[str, int]:
    """Generate synthetic images directly into the final split directories."""
    print(f"[synthetic] rendering {train_n}/{val_n}/{test_n} per class into {out_root}")
    counts = {"train": train_n, "val": val_n, "test": test_n}
    synth_generate(out_root, counts)
    total = (train_n + val_n + test_n) * NUM_CLASSES
    return {"synthetic": total}


def _kaggle_cli_available() -> bool:
    return shutil.which("kaggle") is not None


def add_kaggle(out_root: Path, dataset_slug: str, scratch_dir: Path) -> dict[str, int]:
    """Download a Kaggle dataset, remap any keyword-labelled folders to your
    7 stages, and merge the matched images into the train/val/test splits.

    Requires:
      - ``kaggle`` Python package installed (``pip install kaggle``)
      - ``~/.kaggle/kaggle.json`` containing your real Kaggle credentials.
    """
    counts = {f"kaggle_stage_{i+1}": 0 for i in range(NUM_CLASSES)}
    counts["kaggle_unmapped"] = 0

    if not _kaggle_cli_available():
        print("[kaggle] kaggle CLI not on PATH — skipping. "
              "Install with `pip install kaggle` and create ~/.kaggle/kaggle.json.")
        return counts

    scratch_dir.mkdir(parents=True, exist_ok=True)
    print(f"[kaggle] downloading {dataset_slug} into {scratch_dir}")
    try:
        subprocess.run(
            ["kaggle", "datasets", "download", "-d", dataset_slug,
             "-p", str(scratch_dir), "--unzip"],
            check=True,
        )
    except subprocess.CalledProcessError as exc:
        print(f"[kaggle] download failed ({exc}). "
              "Check your kaggle.json or the dataset slug.")
        return counts

    # Walk every image; use its parent folder name as the raw label.
    all_images = list(_iter_images(scratch_dir))
    print(f"[kaggle] found {len(all_images)} images to remap")

    # Group images by (stage_idx) after remap.
    grouped: list[list[Path]] = [[] for _ in range(NUM_CLASSES)]
    for img in all_images:
        parent_label = img.parent.name
        stage_idx = remap_label(parent_label)
        if stage_idx is None:
            # Fall back to filename-based matching.
            stage_idx = remap_label(img.stem)
        if stage_idx is None:
            counts["kaggle_unmapped"] += 1
            continue
        grouped[stage_idx].append(img)

    # Shuffle each group deterministically and split.
    for stage_idx, imgs in enumerate(grouped):
        if not imgs:
            continue
        imgs_sorted = sorted(imgs)  # deterministic
        train_idx, val_idx, test_idx = _split_indices(len(imgs_sorted))
        for split_name, indices in (("train", train_idx), ("val", val_idx), ("test", test_idx)):
            dst = out_root / split_name / f"stage_{stage_idx + 1}"
            for k, i in enumerate(indices):
                _safe_copy(imgs_sorted[i], dst, prefix=f"kg_s{stage_idx + 1}", idx=k)
        counts[f"kaggle_stage_{stage_idx + 1}"] = len(imgs_sorted)
        print(f"[kaggle] stage_{stage_idx + 1}: {len(imgs_sorted)} images "
              f"(train={len(train_idx)}, val={len(val_idx)}, test={len(test_idx)})")

    return counts


def add_manual(out_root: Path, manual_root: Path) -> dict[str, int]:
    """Merge a manually-labelled directory (manual_root/stage_{1..7}/*.png) into
    the splits. Most useful for fine-tuning on real photos you've collected."""
    counts = {f"manual_stage_{i+1}": 0 for i in range(NUM_CLASSES)}
    if not manual_root.exists():
        print(f"[manual] {manual_root} does not exist — skipping.")
        return counts

    for stage_idx in range(NUM_CLASSES):
        src_dir = manual_root / f"stage_{stage_idx + 1}"
        if not src_dir.exists():
            continue
        imgs = sorted(_iter_images(src_dir))
        if not imgs:
            continue
        train_idx, val_idx, test_idx = _split_indices(len(imgs))
        for split_name, indices in (("train", train_idx), ("val", val_idx), ("test", test_idx)):
            dst = out_root / split_name / f"stage_{stage_idx + 1}"
            for k, i in enumerate(indices):
                _safe_copy(imgs[i], dst, prefix=f"man_s{stage_idx + 1}", idx=k)
        counts[f"manual_stage_{stage_idx + 1}"] = len(imgs)
        print(f"[manual] stage_{stage_idx + 1}: {len(imgs)} real images merged")
    return counts


# ---------------------------------------------------------------- driver
def parse_args():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="data", help="dataset root (default: ./data)")
    ap.add_argument("--synthetic-train", type=int, default=400)
    ap.add_argument("--synthetic-val", type=int, default=80)
    ap.add_argument("--synthetic-test", type=int, default=50)
    ap.add_argument("--kaggle-dataset", default=None,
                    help="kaggle dataset slug, e.g. owner/dataset-name (optional)")
    ap.add_argument("--kaggle-scratch", default=None,
                    help="scratch dir for kaggle downloads (default: <out>/_kaggle_scratch)")
    ap.add_argument("--manual-root", default=None,
                    help="folder of pre-labelled real photos in stage_{1..7}/ layout")
    return ap.parse_args()


def main():
    args = parse_args()
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    summary: dict[str, dict[str, int]] = {}

    summary["synthetic"] = add_synthetic(
        out, args.synthetic_train, args.synthetic_val, args.synthetic_test,
    )

    if args.kaggle_dataset:
        scratch = Path(args.kaggle_scratch or (out / "_kaggle_scratch"))
        summary["kaggle"] = add_kaggle(out, args.kaggle_dataset, scratch)

    if args.manual_root:
        summary["manual"] = add_manual(out, Path(args.manual_root))

    # Final counts per split per stage — read from disk so the manifest reflects
    # the real on-disk state, not the in-memory tally.
    final_counts: dict[str, dict[str, int]] = {}
    for split in ("train", "val", "test"):
        final_counts[split] = {}
        for stage_idx in range(NUM_CLASSES):
            d = out / split / f"stage_{stage_idx + 1}"
            n = sum(1 for _ in _iter_images(d)) if d.exists() else 0
            final_counts[split][f"stage_{stage_idx + 1}"] = n

    manifest = {
        "stages": [s.name for s in STAGES],
        "sources": summary,
        "final_counts": final_counts,
    }
    (out / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print()
    print("=== final dataset ===")
    for split, by_stage in final_counts.items():
        total = sum(by_stage.values())
        print(f"  {split}: {total} images  {by_stage}")
    print(f"manifest written to {out / 'manifest.json'}")


if __name__ == "__main__":
    main()
